Updated Readme.md
Executing without sudo will give the following Error:
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

So it is necessary to run installation with sudo.